### PR TITLE
[WM-1858] add support for auto-delete queues

### PR DESCRIPTION
**Pull request by torypeterschild**
**changes in this pr**
https://renttherunway.jira.com/browse/WM-1858

Add support for auto-delete queues.

See also https://renttherunway.jira.com/wiki/spaces/OC/pages/1807090532/cloud-ready+panda+HA

### CODE REVIEW

**Review by michiakig — APPROVED** [review]

**Comment by stephen-hand-RTR** [comment]
I'm not sure why is the functionality to create named, temporary queues is required? 

Looking the ticket, it seems like the existing conduit 'dynamic queues' which create a temporary queue with a generated name would satisfy the requirement?

**Comment by torypeterschild** [comment]
@stephen-hand-RTR 

The **primary** purpose here is to add support for temporary queues to the "auto create and bind" functionality, which panda uses on startup to

- create a queue and bind it to consistent hash exchange `fulfillment-group-update`
- create a queue and bind it to consistent hash exchange `order-group-update`

We're reliant on "auto create and bind" because in the cloud we're not guaranteed to have the same number of instances, so we can't, for example, just declare three queues and reuse them across deploys. 

It would have satisfied most requirements to add support for temporary queues with generated names to "auto create and bind", but using named queues 

- allows us to continue using signal fx detectors to alert when one of the sharded queues has no consumers
- makes troubleshooting a bit easier 


let me know if that all makes sense!

**Comment by stephen-hand-RTR** [comment]
> @stephen-hand-RTR
> 
> The **primary** purpose here is to add support for temporary queues to the "auto create and bind" functionality, which panda uses on startup to
> 
> * create a queue and bind it to consistent hash exchange `fulfillment-group-update`
> * create a queue and bind it to consistent hash exchange `order-group-update`
> 
> We're reliant on "auto create and bind" because in the cloud we're not guaranteed to have the same number of instances, so we can't, for example, just declare three queues and reuse them across deploys.
> 
> It would have satisfied most requirements to add support for temporary queues with generated names to "auto create and bind", but using named queues
> 
> * allows us to continue using signal fx detectors to alert when one of the sharded queues has no consumers
> * makes troubleshooting a bit easier
> 
> let me know if that all makes sense!

I think I understand. 

My concern is that prior to this commit we had a confusing API with 'autocreate and bind' (for durable named queues & exchanges created on the fly) and 'dynamic queues' (for temporary queues created on the fly). 

Now we will have 'auto created temporary queues' which blurs the lines between 'auto create and bind queues' and 'dynamic queues' further.

I'm not sure there's a 'neat' solution that would not break compatibility with the current API, but could we change the `ConsumerBuilder` API so that the 'autoDeleteQueue' flag is set in an additional parameter in an overload of the `autoCreateAndBind` builder method rather than it's own builder method? 

At least that way it would be obvious that the 'autoDeleteQueues' flag ONLY affects autoCreateAndBind behaviour, and does not affect queues created when using the `dynamicQueues` option (or existing queues when neither option is being used).

**Comment by torypeterschild** [comment]
@stephen-hand-RTR 

> could we change the ConsumerBuilder API so that the 'autoDeleteQueue' flag is set in an additional parameter in an  overload of the autoCreateAndBind builder method rather than it's own builder method?
> 
> At least that way it would be obvious that the 'autoDeleteQueues' flag ONLY affects autoCreateAndBind behaviour, and does not affect queues created when using the dynamicQueues option (or existing queues when neither option is being used).

yep, good thought — updated when you have a chance to take a look!

**Review by stephen-hand-RTR — APPROVED** [review]
Thanks Tory!

**Review by michiakig — APPROVED** [review]

**Pull request merged**
